# Generated by Django 2.2.5 on 2021-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('plano', models.CharField(max_length=10, verbose_name='Plano')),
                ('mensalidade', models.TextField(max_length=40, verbose_name='Mensalidade')),
                ('quantidade', models.TextField(max_length=40, verbose_name='Quantidade de usuários')),
                ('capacidade', models.TextField(max_length=40, verbose_name='Capacidade')),
                ('suporte', models.TextField(max_length=40, verbose_name='Suporte')),
                ('atualizacoes', models.TextField(max_length=40, verbose_name='Atualizações')),
                ('icone', models.CharField(choices=[('lni-package', 'Pacote'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], max_length=20, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
